// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ranjha-mapselect/ContemporaryDesi.tsx": () => import("../components/mockups/ranjha-mapselect/ContemporaryDesi.tsx"),
  "./components/mockups/ranjha-mapselect/MughalCourt.tsx": () => import("../components/mockups/ranjha-mapselect/MughalCourt.tsx"),
  "./components/mockups/ranjha-mapselect/TruckArt.tsx": () => import("../components/mockups/ranjha-mapselect/TruckArt.tsx")
};
